name: Cloud Deployment

on:
  push:
    # paths:
    #   - 'Cloud/**' # The cloud server app exists in this directory
    branches:
      - cloud_deployment

env:
  CLOUD_DIR: Cloud
  DOCKER_IMG: "cloud-img"
  TAR_FILE: "cloud.tar"


jobs:
  build:

    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository Code
        uses: actions/checkout@v2

      - name: Building the cloud application
        run: g++ -o out server.cpp
        working-directory: ${{ env.CLOUD_DIR }}


  deploy:

    name: Deploying on cloud server
    runs-on: ubuntu-latest

    needs: [ build ]
    # defaults:
    #   run:
    #     working-directory: ${{ env.CLOUD_DIR }}

    steps:
      
      - name: Checkout the Repository Code
        uses: actions/checkout@v2

      - name: Send the requered files to the cloud server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_HOST}}
          username: ${{ secrets.AZURE_USER}}
          password: ${{ secrets.AZURE_PASS}}
          port: 22
          source: "./${{ env.CLOUD_DIR }}/Dockerfile"
          target: "~/home/${{ secrets.AZURE_USER}}"

      # Converting the Dockerfile to a Docker image
      - name: Compiling the Dockerfile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST}}
          username: ${{ secrets.AZURE_USER}}
          password: ${{ secrets.AZURE_PASS}}
          port: 22
          script: ssudo docker build -t  ${{ env.DOCKER_IMG }}  ./

      - name: Running the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST}}
          username: ${{ secrets.AZURE_USER}}
          password: ${{ secrets.AZURE_PASS}}
          port: 22
          script: sudo docker run ${{ env.DOCKER_IMG }}

