name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  config:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    #  use ubuntu-20.04
    runs-on: ubuntu-20.04


    steps:
    - name: Checkout the Repository Code
      uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    - name: Run
      working-directory: ${{github.workspace}}/build/App 
      run: ./Adaptive_Platform
    

    - name: Test
      working-directory: ${{github.workspace}}/build/Testing
      run: ./Adaptive_Platform-ut



  web_generate:
    name: Generate The documentationon the website using Doxygen
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the Repository Code
      uses: actions/checkout@v3
    - name: Generate the documentation
      run: |
        sudo apt-get install doxygen graphviz -y 
        doxygen doxygen.conf
    - name: push the documentation to the website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        # copy the data from doc/html and overwrite the root of the gh-pages branch
        publish_dir: ${{github.workspace}}/doc/html
        publish_branch: gh-pages
        # clear all files on the gh-pages branch and push only the files in the publish_dir
        force_orphan: true
        # commit the changes to gh-pages branch
        commit_message: 'update the documentation'
        user_name: ahmed192a
        user_email: ah1326996@gmail.com

        



